# -*- coding: utf-8 -*-
"""agricycle_sim.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1en0csVnudFWbSsMGlo8qa6x37bqHSFIB
"""

def  agricycle_ussd_menu():
    print("--- AGRICYCLE USSD GATEWAY SIMULATION ---")
    print("Dialing *384*2026#...\n")

    print("WELCOME TO AGRICYCLE")
    print("1. Register Biomass Batch")
    print("2. Check Carbon Credits Balance")
    print("3. View Biochar Collection Status")

    choice = input("\nEnter option number: ")

    if choice == "1":
        register_biomass()
    elif choice == "2":
        check_credits()
    elif choice == "3":
        check_status()
    else:
        print("Invalid choice. Session ended.")

def register_biomass():
    print("\n--- BIOMASS REGISTRATION ---")
    farmer_id = input("Enter Farmer Cooperative ID: ")
    feedstock_type = input("Enter Feedstock Type (e.g., Maize Stalks, Cobs): ")
    weight = input("Enter Estimated Weight (in KG): ")

    print("\n[SUCCESS] Data transmitted to secure cloud ledger!")
    print(f"ID: {farmer_id} | Material: {weight}kg of {feedstock_type}")
    print("Status: Logged for Pyrolysis Verification & Carbon Credit Generation.")

def check_credits():
    print("\n--- CARBON CREDIT WALLET ---")
    phone = input("Enter Registered Mobile Number: ")
    print(f"Fetching balance for {phone}...")
    print("Balance: 0.85 Verified Carbon Removal Credits (ZMW 340.00 equivalent value pending payout).")

def check_status():
    print("\n--- BIOCHAR STATUS ---")
    print("Your batch is queued for conversion at the local kiln unit. Return rate: 3 bags of nutrient biochar ready in 48 hours.")

if __name__ == "__main__":
    agricycle_ussd_menu()